name: Release Windows Executable

# When a release is created, the workflow is triggered
# We can not use the event release created because it is not triggered when the GITHUB_TOKEN is used
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap and create virtual environment
        run: .\bootstrap.ps1
        shell: powershell
      - name: Install Dependencies
        run: .venv/Scripts/poetry install --with=dev
        shell: powershell
      - name: Create windows executable
        run: .\build_exe.ps1
        shell: powershell
      - name: Get the latest tag from the git history
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Upload windows executable to GitHub releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          tag_name: ${{ steps.get_tag.outputs.tag }}
