name: Release Windows Executable

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap and create virtual environment
        run: .\bootstrap.ps1
        shell: powershell
      - name: Install Dependencies
        run: .venv/Scripts/poetry install --with=dev
        shell: powershell
      - name: Run PyInstaller
        run: .venv/Scripts/poetry run pyinstaller build_exe.spec
        shell: powershell
      - name: Zip windows executable
        run: Compress-Archive -Path dist/yanga.exe -DestinationPath dist/yanga.windows-amd64.${{github.ref_name}}.zip
        shell: powershell
      - name: Upload windows executable to GitHub releases
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          files: dist/yanga.windows-amd64.${{github.ref_name}}.zip
